import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import PricingModal from "../components/PricingModal";

const plans = [
  {
    id: "free",
    name: "Free",
    price: "₹0",
    period: "forever",
    features: ["5 generations/month", "Blog, LinkedIn, Email", "4 tones", "History"],
    cta: "Get started free",
    highlight: false,
  },
  {
    id: "pro",
    name: "Pro",
    price: "₹1",
    period: "per month",
    features: ["100 generations/month", "Blog, LinkedIn, Email", "4 tones", "Full history", "Priority support"],
    cta: "Upgrade to Pro",
    highlight: true,
  },
  {
    id: "business",
    name: "Business",
    price: "₹2",
    period: "per month",
    features: ["500 generations/month", "Blog, LinkedIn, Email", "4 tones", "Full history", "Priority support", "Team access (soon)"],
    cta: "Get Business",
    highlight: false,
  },
];

export default function Landing() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [showModal, setShowModal] = useState(false);

  const handlePlanClick = (planId) => {
    if (planId === "free") {
      navigate("/signup");
      return;
    }
    if (user) {
      setShowModal(true);
    } else {
      navigate("/signup");
    }
  };

  return (
    <div className="min-h-screen bg-zinc-950 text-white">

      {/* Navbar */}
      <nav className="border-b border-zinc-800 px-6 py-4 flex items-center justify-between">
        <h1 className="text-xl font-bold">
          Content<span className="text-zinc-400">Craft</span>
        </h1>
        <div className="flex items-center gap-4">
          <a href="#pricing" className="text-zinc-400 hover:text-white text-sm transition-colors">
            Pricing
          </a>
          <Link to="/login" className="text-zinc-400 hover:text-white text-sm transition-colors">
            Sign in
          </Link>
          <Link
            to="/signup"
            className="bg-white text-zinc-900 text-sm font-semibold px-4 py-2 rounded-lg hover:bg-zinc-200 transition-all"
          >
            Get started free
          </Link>
        </div>
      </nav>

      {/* Hero */}
      <section className="max-w-4xl mx-auto px-6 pt-24 pb-16 text-center">
        <div className="inline-flex items-center gap-2 bg-zinc-900 border border-zinc-800 rounded-full px-4 py-1.5 text-xs text-zinc-400 mb-8">
          <span className="w-1.5 h-1.5 bg-green-500 rounded-full"></span>
          Powered by Gemini AI
        </div>
        <h1 className="text-6xl font-bold leading-tight tracking-tight mb-6">
          Generate content
          <br />
          <span className="text-zinc-500">in seconds, not hours</span>
        </h1>
        <p className="text-zinc-400 text-xl max-w-2xl mx-auto mb-10">
          Blog posts, LinkedIn captions, cold emails — all generated by AI with your tone, your style, instantly.
        </p>
        <div className="flex items-center justify-center gap-4">
          <Link
            to="/signup"
            className="bg-white text-zinc-900 font-bold px-8 py-3.5 rounded-xl hover:bg-zinc-200 transition-all text-lg"
          >
            Start for free ⚡
          </Link>
          <Link
            to="/login"
            className="border border-zinc-700 text-zinc-300 font-medium px-8 py-3.5 rounded-xl hover:border-zinc-500 hover:text-white transition-all text-lg"
          >
            Sign in
          </Link>
        </div>
        <p className="text-zinc-600 text-sm mt-4">5 free generations — no credit card required</p>
      </section>

      {/* Features */}
      <section className="max-w-5xl mx-auto px-6 py-16">
        <h2 className="text-3xl font-bold text-center mb-12">Everything you need to create content fast</h2>
        <div className="grid grid-cols-3 gap-6">
          {[
            { icon: "📝", title: "Blog Posts", desc: "Full SEO-optimized blog posts with headings, intro, and conclusion." },
            { icon: "💼", title: "LinkedIn Captions", desc: "Scroll-stopping posts with hooks, insights, and hashtags." },
            { icon: "📧", title: "Cold Emails", desc: "High-converting outreach emails with subject lines and CTAs." },
          ].map((f) => (
            <div key={f.title} className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6 hover:border-zinc-600 transition-colors">
              <span className="text-3xl">{f.icon}</span>
              <h3 className="text-lg font-semibold mt-3 mb-2">{f.title}</h3>
              <p className="text-zinc-500 text-sm leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Tone Feature */}
      <section className="max-w-5xl mx-auto px-6 py-16 border-t border-zinc-900">
        <div className="grid grid-cols-2 gap-12 items-center">
          <div>
            <h2 className="text-3xl font-bold mb-4">Your tone, your voice</h2>
            <p className="text-zinc-400 leading-relaxed mb-6">
              Choose from 4 distinct tones to match your brand personality — from boardroom professional to internet-native Gen-Z.
            </p>
            <div className="grid grid-cols-2 gap-3">
              {["💼 Professional", "😊 Casual", "😂 Funny", "🔥 Gen-Z"].map((t) => (
                <div key={t} className="bg-zinc-900 border border-zinc-800 rounded-lg px-4 py-2.5 text-sm text-zinc-300">
                  {t}
                </div>
              ))}
            </div>
          </div>
          <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6">
            <div className="flex items-center gap-2 mb-4">
              <div className="w-3 h-3 rounded-full bg-red-500"></div>
              <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
              <div className="w-3 h-3 rounded-full bg-green-500"></div>
            </div>
            <div className="space-y-2">
              <div className="h-3 bg-zinc-800 rounded w-3/4"></div>
              <div className="h-3 bg-zinc-800 rounded w-full"></div>
              <div className="h-3 bg-zinc-800 rounded w-5/6"></div>
              <div className="h-3 bg-zinc-800 rounded w-2/3"></div>
              <div className="h-3 bg-zinc-800 rounded w-full"></div>
              <div className="h-3 bg-zinc-800 rounded w-4/5"></div>
            </div>
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="max-w-5xl mx-auto px-6 py-16 border-t border-zinc-900">
        <h2 className="text-3xl font-bold text-center mb-4">Simple pricing</h2>
        <p className="text-zinc-500 text-center mb-12">Start free, upgrade when you need more</p>
        <div className="grid grid-cols-3 gap-6">
          {plans.map((plan) => (
            <div
              key={plan.name}
              className={`relative rounded-2xl p-6 border flex flex-col ${
                plan.highlight
                  ? "bg-white text-zinc-900 border-white"
                  : "bg-zinc-900 text-white border-zinc-800"
              }`}
            >
              {plan.highlight && (
                <span className="absolute -top-3 left-1/2 -translate-x-1/2 bg-zinc-900 text-white text-xs font-bold px-3 py-1 rounded-full border border-zinc-700">
                  MOST POPULAR
                </span>
              )}
              <h3 className="font-bold text-lg mb-1">{plan.name}</h3>
              <div className="flex items-end gap-1 mb-1">
                <span className="text-4xl font-bold">{plan.price}</span>
              </div>
              <p className={`text-sm mb-6 ${plan.highlight ? "text-zinc-600" : "text-zinc-500"}`}>
                {plan.period}
              </p>
              <ul className="space-y-2 mb-6 flex-1">
                {plan.features.map((f) => (
                  <li key={f} className="flex items-center gap-2 text-sm">
                    <svg className="w-4 h-4 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                    {f}
                  </li>
                ))}
              </ul>
              <button
                onClick={() => handlePlanClick(plan.id)}
                className={`w-full text-center font-semibold py-2.5 rounded-xl transition-all text-sm ${
                  plan.highlight
                    ? "bg-zinc-900 text-white hover:bg-zinc-800"
                    : "bg-zinc-800 text-white hover:bg-zinc-700"
                }`}
              >
                {plan.cta}
              </button>
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-zinc-900 px-6 py-8 text-center">
        <p className="text-zinc-600 text-sm">
          © 2024 ContentCraft. Built with ⚡ for creators.
        </p>
      </footer>

      {/* Pricing Modal */}
      {showModal && <PricingModal onClose={() => setShowModal(false)} />}
    </div>
  );
}